---
name: "AzOps - Push"

on:
  #
  # Push
  # Automated workflow trigger when a merge
  # commit enters the main branch.
  #

  push:
    branches:
      - main
    paths:
      - "root/**"

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  #
  # Credentials
  #

  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  push:
    #
    # Push
    #

    name: "Push"
    runs-on: ubuntu-20.04
    environment: prod

    steps:
      #
      # Checkout
      # Checks-out the repository
      #

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #
      # Dependencies
      # Install required runtime modules
      #

      - name: "Dependencies"
        shell: pwsh
        run: |
          Install-Module -Name "AzOps" -Force

      #
      # Connect
      # Authenticate Azure context
      #

      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID}}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      #
      # Diff
      # List index changes
      #

      - name: "Diff"
        shell: bash
        run: |
          if [ ! -z "$(git diff --name-status HEAD^ HEAD)" ]; then
            echo $(git diff --name-status HEAD^ HEAD)
            git diff --name-status HEAD^ HEAD > /tmp/diff.txt
            if [ ! -z "$(git diff --diff-filter=D HEAD^ HEAD)" ]; then
              echo $(git diff --diff-filter=D HEAD^ HEAD  --no-prefix | grep ^- | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | less -r)
              git diff --diff-filter=D HEAD^ HEAD --no-prefix | grep ^- | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | less -r > /tmp/diffdeletedfiles.txt
            fi
          else
            echo "The validation pipeline failed because there is currently no change to be processed"
            exit 1
          fi

      #
      # Deploy
      # Initial deployment of any index changes
      #

      - name: "Deploy"
        shell: pwsh
        run: |
          Initialize-AzOpsEnvironment
          Import-PSFConfig -Path settings.json -Schema MetaJson -EnableException
          $diff = Get-Content -Path /tmp/diff.txt
          $module = Get-Module -Name AzOps
          if(Test-Path -Path "/tmp/diffdeletedfiles.txt") {
            $diffdeletedfiles = Get-Content -Path /tmp/diffdeletedfiles.txt
            $module.Invoke({ Invoke-AzOpsPush -ChangeSet $diff -DeleteSetContents $diffdeletedfiles })
          }
          else {
            $module.Invoke({ Invoke-AzOpsPush -ChangeSet $diff })
          }
          Get-Job | Remove-Job -Force
