name: "Validate or Deploy"

inputs:
  deploy:
    default: false
  name:
    required: true
on:
  workflow_call:

runs:
  using: 'composite'
  steps:
      #
      # Diff
      # List index changes
      #
      
      - name: "Diff"
        shell: pwsh
        run: |
          $gitDiff = git diff --name-status HEAD^ HEAD
          if ($null -ne $gitDiff) {
            $gitDiff | Write-Host
            $gitDiff | Out-File -FilePath '/tmp/diff.txt'
            
            $deletedContent = git diff --diff-filter=D HEAD^ HEAD --no-prefix --no-renames
            if($null -ne $deletedContent) {
                $deletedContent = $deletedContent -match '^-' -replace '^([^-+ ]*)[-+ ]', '$1'
                Write-Host '##[group]Deleted files content'
                $deletedContent | Write-Host
                Write-Host '##[endgroup]'
                $deletedContent | Out-File -FilePath '/tmp/diffdeletedfiles.txt'
            }
          }
          else {
            Write-Error -Message 'The validation pipeline failed because there is currently no change to be processed'
            exit 1
          }

      #
      # CustomSorting
      # If CustomSorting is enabled, sort files in diff by the .order file in each directory
      #

      - name: "CustomSorting"
        shell: pwsh
        if: ${{ env.AZOPS_CUSTOM_SORT_ORDER == 'true' }}
        run: |
          ./.scripts/customSorting.ps1

      #
      # Deploy
      # Initial deployment of any index changes
      #

      - name: ${{ inputs.name }}
        shell: pwsh
        run: |
          Import-PSFConfig -Path settings.json -Schema MetaJson -EnableException
          $RunWhatIf = -not ('${{inputs.deploy}}' -eq 'true')
          $diff = Get-Content -Path /tmp/diff.txt
          if(Test-Path -Path "/tmp/diffdeletedfiles.txt") {
            $diffdeletedfiles = Get-Content -Path /tmp/diffdeletedfiles.txt
            Invoke-AzOpsPush -ChangeSet $diff -DeleteSetContents $diffdeletedfiles -WhatIf:$RunWhatIf
          } 
          else {
            Invoke-AzOpsPush -ChangeSet $diff -WhatIf:$RunWhatIf
          }
          Get-Job | Remove-Job -Force
