---
name: 'AzOps - Pull'

trigger: none

# Temporary

pool:
  name: 'Azure Self-hosted Pipelines'

jobs:

- job: pull

  #
  # Pull
  #

  displayName: 'Pull'
  workspace:
        clean: all
  steps:

  #
  # Checkout
  # Checks-out the repository
  #

  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  #
  # Configure
  # Set global options
  #

  - task: Bash@3
    displayName: 'Configure'
    inputs:
      targetType: 'inline'
      script: |
          git config user.name 'Azure DevOps'
          git config user.email 'azuredevops@microsoft.com'

  #
  # Checkout
  # Switch branches
  #

  - task: Bash@3
    displayName: 'Checkout'
    inputs:
      targetType: 'inline'
      script: |
        git checkout -b automated

  #
  # Dependencies
  # Install required runtime modules
  #

  - task: PowerShell@2
    displayName: 'Dependencies'
    inputs:
      targetType: 'inline'
      script: |
        Install-Module -Name "AzOps" -AllowPrerelease -Force
        Install-Module -Name @("Az.Accounts", "Az.Billing", "Az.Resources", "PSFramework") -Force

  #
  # Connect
  # Authenticate Azure context
  #

  - task: PowerShell@2
    displayName: 'Connect'
    inputs:
      targetType: 'inline'
      script: |
          $credential = New-Object System.Management.Automation.PSCredential `
            -ArgumentList $(ARM_CLIENT_ID), (ConvertTo-SecureString -String $(ARM_CLIENT_SECRET) -AsPlainText -Force)
          Connect-AzAccount `
            -TenantId $(ARM_TENANT_ID) -ServicePrincipal -Credential $credential -SubscriptionId $(ARM_SUBSCRIPTION_ID)

  #
  # Initialize
  # Generate new state data
  #

  - task: PowerShell@2
    displayName: 'Initialize'
    inputs:
      targetType: 'inline'
      script: |
          Import-PSFConfig -Path settings.json -Schema MetaJson
          Initialize-AzOpsRepository -Rebuild
          Get-Job | Remove-Job -Force

  #
  # Status
  # Check for data changes
  #

  - task: Bash@3
    displayName: 'Status'
    inputs:
      targetType: 'inline'
      script: |
        STATUS=$(git status --short)
        if [ -z "$STATUS" ]
        then
          echo '##vso[task.setvariable variable=state]continue'
        else
          echo '##vso[task.setvariable variable=state]stop'
        fi

  #
  # Add
  # Add file content to index
  #

  - task: Bash@3
    displayName: 'Add'
    condition: contains(variables['state'], 'stop')
    inputs:
      targetType: 'inline'
      script: |
        git add ./azops

  #
  # Commit
  # Record changes to the repository
  #

  - task: Bash@3
    displayName: 'Commit'
    condition: contains(variables['state'], 'stop')
    inputs:
      targetType: 'inline'
      script: |
        git commit -m 'Automated commit'

  #
  # Push
  # Update remote refs along with associated objects
  #

  - task: Bash@3
    displayName: 'Push'
    condition: contains(variables['state'], 'stop')
    inputs:
      targetType: 'inline'
      script: |
        git push origin automated -f

  #
  # Merge
  # Update remote refs along with associated objects
  #

  - task: Bash@3
    displayName: 'Merge'
    condition: contains(variables['state'], 'stop')
    inputs:
      targetType: 'inline'
      script: |
        az repos pr create \
          --title "Automated State" \
          --source-branch "automated" \
          --target-branch "main" \
          --squash true \
          --delete-source-branch true \
          --auto-complete true
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
