---
name: "AzOps - Push"

trigger: none

# Temporary

pool:
  name: 'Azure Self-hosted Pipelines'

jobs:

- job: pre

  #
  # Pre
  # - Before running the resource deployment,
  # - we need to validate the repository state
  # - is up to date and we won't encounter conflicts.
  #

  displayName: 'Pre'
  condition: and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['System.PullRequest.SourceBranch'], 'refs/heads/automated'))
  workspace:
    clean: all
  steps:

  #
  # Checkout
  # Checks-out the repository
  #

  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  #
  # Dependencies
  # Install required runtime modules
  #

  - task: PowerShell@2
    displayName: 'Dependencies'
    inputs:
      targetType: 'inline'
      script: |
        Install-Module -Name "AzOps" -AllowPrerelease -Force
        Install-Module -Name @("Az.Accounts", "Az.Billing", "Az.Resources", "PSFramework") -Force

  #
  # Connect
  # Authenticate Azure context
  #

  - task: PowerShell@2
    displayName: 'Connect'
    inputs:
      targetType: 'inline'
      script: |
          $credential = New-Object System.Management.Automation.PSCredential `
            -ArgumentList $(ARM_CLIENT_ID), (ConvertTo-SecureString -String $(ARM_CLIENT_SECRET) -AsPlainText -Force)
          Connect-AzAccount `
            -TenantId $(ARM_TENANT_ID) -ServicePrincipal -Credential $credential -SubscriptionId $(ARM_SUBSCRIPTION_ID)

  #
  # Initialize
  # Generate new state data
  #

  - task: PowerShell@2
    displayName: 'Initialize'
    inputs:
      targetType: 'inline'
      script: |
          Import-PSFConfig -Path settings.json -Schema MetaJson
<<<<<<< HEAD
          Initialize-AzOpsRepository -Rebuild
=======
          Initialize-AzOpsRepository
>>>>>>> main
          Get-Job | Remove-Job -Force

  #
  # Diff
  # List index changes
  #

  - task: Bash@3
    displayName: 'Diff'
<<<<<<< HEAD
    name: diff
=======
>>>>>>> main
    inputs:
      targetType: 'inline'
      script: |
        DIFF=$(git diff --ignore-space-at-eol --name-status)
        if [ -z "$DIFF" ]
        then
          echo $DIFF
<<<<<<< HEAD
          echo "##vso[task.setvariable variable=state;isOutput=true]continue"
        else
          echo $DIFF
          echo "##vso[task.setvariable variable=state;isOutput=true]stop"
=======
          echo "##vso[task.setvariable variable=state]continue"
        else
          echo $DIFF
          echo "##vso[task.setvariable variable=state]stop"
>>>>>>> main
        fi

  #
  # Issue
  # Write issue and stop workflow
  #

  - task: Bash@3
    displayName: 'Issue'
<<<<<<< HEAD
    condition: contains(variables['diff.state'], 'stop')
=======
    condition: contains(variables['state'], 'stop')
>>>>>>> main
    inputs:
      targetType: 'inline'
      script: |
        curl --request POST \
        --header "Authorization: Bearer $(System.AccessToken)" \
        --header "Content-Type: application/json" \
        --data '{ "comments": [ { "parentCommentId": 0, "content": "Hello!", "commentType": 1 } ], "status": 1 }' \
<<<<<<< HEAD
        --url $(System.CollectionUri)/$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=6.0
=======
        --url https://dev.azure.com/$(organization)/$(project)/_apis/git/repositories/$(repository)/pullRequests/$(pullRequest)/threads?api-version=6.0
>>>>>>> main

- job: push

  #
  # Push
<<<<<<< HEAD
  # -
  # -
  # -
  #

  displayName: 'Push'
  condition: contains(dependencies.pre.outputs['diff.state'], 'continue')
=======
  # - Before running the resource deployment,
  # - we need to validate the repository state
  # - is up to date and we won't encounter conflicts.
  #

  displayName: 'Push'
  condition: contains(variables['state'], 'continue')
>>>>>>> main
  dependsOn: pre
  workspace:
    clean: all
  steps:

  #
  # Checkout
  # Checks-out the repository
  #

  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  #
  # Dependencies
  # Install required runtime modules
  #

  - task: PowerShell@2
    displayName: 'Dependencies'
    inputs:
      targetType: 'inline'
      script: |
        Install-Module -Name "AzOps" -AllowPrerelease -Force
        Install-Module -Name @("Az.Accounts", "Az.Billing", "Az.Resources", "PSFramework") -Force

  #
  # Connect
  # Authenticate Azure context
  #

  - task: PowerShell@2
    displayName: 'Connect'
    inputs:
      targetType: 'inline'
      script: |
          $credential = New-Object System.Management.Automation.PSCredential `
            -ArgumentList $(ARM_CLIENT_ID), (ConvertTo-SecureString -String $(ARM_CLIENT_SECRET) -AsPlainText -Force)
          Connect-AzAccount `
            -TenantId $(ARM_TENANT_ID) -ServicePrincipal -Credential $credential -SubscriptionId $(ARM_SUBSCRIPTION_ID)

  #
  # Diff
  # List index changes
  #

  - task: Bash@3
    displayName: 'Diff'
    inputs:
      targetType: 'inline'
      script: |
        git diff origin/main --name-status > /tmp/diff.txt

  #
  # Deploy
  # Initial deployment of any index changes
  #

  - task: PowerShell@2
    displayName: 'Deploy'
    inputs:
      targetType: 'inline'
      script: |
<<<<<<< HEAD
        Import-PSFConfig -Path settings.json -Schema MetaJson
        Initialize-AzOpsEnvironment
=======
        Initialize-AzOpsEnvironment
        Import-PSFConfig -Path settings.json -Schema MetaJson
>>>>>>> main
        $diff = Get-Content -Path /tmp/diff.txt
        $module = Get-Module -Name AzOps
        $module.Invoke({ Invoke-AzOpsChange -ChangeSet $diff })
        Get-Job | Remove-Job -Force

- job: post

  #
  # Post
<<<<<<< HEAD
  # -
  # -
  # -
  #

  displayName: 'Post'
  condition: contains(dependencies.pre.outputs['diff.state'], 'continue')
=======
  # - Before running the resource deployment,
  # - we need to validate the repository state
  # - is up to date and we won't encounter conflicts.
  #

  displayName: 'Post'
  condition: contains(variables['state'], 'continue')
>>>>>>> main
  dependsOn: push
  workspace:
    clean: all
  steps:

  #
  # Checkout
  # Checks-out the repository
  #

  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  #
  # Configure
  # Set global options
  #

  - task: Bash@3
    displayName: 'Configure'
    inputs:
      targetType: 'inline'
      script: |
          git config user.name "Azure DevOps"
          git config user.email "azuredevops@microsoft.com"

  #
  # Switch
  # Change working branch
  #

  - task: Bash@3
    displayName: 'Switch'
    inputs:
      targetType: 'inline'
      script: |
<<<<<<< HEAD
        sourceBranchName=$(echo $(System.PullRequest.SourceBranch) | sed 's:refs/heads/::')
        git switch -c $sourceBranchName
=======
        git switch -c $(branch)
>>>>>>> main

  #
  # Dependencies
  # Install required runtime modules
  #

  - task: PowerShell@2
    displayName: 'Dependencies'
    inputs:
      targetType: 'inline'
      script: |
        Install-Module -Name "AzOps" -AllowPrerelease -Force
        Install-Module -Name @("Az.Accounts", "Az.Billing", "Az.Resources", "PSFramework") -Force

  #
  # Connect
  # Authenticate Azure context
  #

  - task: PowerShell@2
    displayName: 'Connect'
    inputs:
      targetType: 'inline'
      script: |
          $credential = New-Object System.Management.Automation.PSCredential `
            -ArgumentList $(ARM_CLIENT_ID), (ConvertTo-SecureString -String $(ARM_CLIENT_SECRET) -AsPlainText -Force)
          Connect-AzAccount `
            -TenantId $(ARM_TENANT_ID) -ServicePrincipal -Credential $credential -SubscriptionId $(ARM_SUBSCRIPTION_ID)

  #
  # Initialize
  # Generate new state data
  #

  - task: PowerShell@2
    displayName: 'Initialize'
    inputs:
      targetType: 'inline'
      script: |
          Import-PSFConfig -Path settings.json -Schema MetaJson
<<<<<<< HEAD
          Initialize-AzOpsRepository -Rebuild
          Get-Job | Remove-Job -Force
=======
          Initialize-AzOpsRepository
>>>>>>> main

  #
  # Add
  # Add file content to index
  #

  - task: Bash@3
    displayName: 'Add'
    inputs:
      targetType: 'inline'
      script: |
        git add ./azops

  #
  # Commit
  # Record changes to the repository
  #

  - task: Bash@3
    displayName: 'Commit'
    inputs:
      targetType: 'inline'
      script: |
<<<<<<< HEAD
        git commit -m "Automated commit" -m "[skip ci]"
=======
        git commit -m "Automated commit"
>>>>>>> main

  #
  # Push
  # Update remote refs along with associated objects
  #

  - task: Bash@3
    displayName: 'Push'
    inputs:
      targetType: 'inline'
      script: |
<<<<<<< HEAD
        sourceBranchName=$(echo $(System.PullRequest.SourceBranch) | sed 's:refs/heads/::')
        git push origin $sourceBranchName  -f
=======
        git push origin $(branch)  -f
>>>>>>> main
