---
name: "AzOps - Push"

#
# Triggers
# Automated triggers are configured via Branch Policies
# within Azure Repos. It's also recommended to manually
# disable CI triggers with overrides.
#

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - root

variables:

  #
  # Shared variables
  # Include shared variables from the 'vars.yml' file
  # to not have to repeat them in every pipeline.
  #

  - template: .templates/vars.yml

jobs:

  - job: push

    #
    # Push
    # Before running the resource deployment,
    # we need to validate the repository state
    # is up to date and we won't encounter conflicts.
    #

    displayName: "Push"
    pool:
      vmImage: ubuntu-20.04

    steps:

      #
      # Shared steps
      # Include shared steps from the 'shared.yml' file
      # to not have to repeat them in every pipeline.
      #

      - template: .templates/sharedSteps.yml
        parameters:
          AZOPS_MODULE_VERSION: ${{ variables['AZOPS_MODULE_VERSION'] }}
          modulesFolder: ${{ variables['modulesFolder'] }}
          ARM_CLIENT_ID: ${{ variables['ARM_CLIENT_ID'] }}
          ARM_CLIENT_SECRET: ${{ variables['ARM_CLIENT_SECRET'] }}
          ARM_SUBSCRIPTION_ID: ${{ variables['ARM_SUBSCRIPTION_ID'] }}
          ARM_TENANT_ID: ${{ variables['ARM_TENANT_ID'] }}

      #
      # Deploy
      # Deploy any templates changed in the last commit
      #

      - template: .templates/validate-deploy.yml
        parameters:
          deploy: true
          modulesFolder: ${{ variables['modulesFolder'] }}