---
name: "AzOps - Push"

#
# Triggers
# Automated triggers are configured via Branch Policies
# within Azure Repos. It's also recommended to manually
# disable CI triggers with overrides.
#

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - root

variables:

  #
  # Credentials
  # This reference is to the Variable Group which needs
  # to be created which will contain the following values.
  #
  # - ARM_TENANT_ID
  # - ARM_SUBSCRIPTION_ID
  # - ARM_CLIENT_ID
  # - ARM_CLIENT_SECRET
  #

  - group: credentials

jobs:

  - job: push

    #
    # Push
    # Before running the resource deployment,
    # we need to validate the repository state
    # is up to date and we won't encounter conflicts.
    #

    displayName: "Push"
    pool:
      vmImage: ubuntu-20.04

    steps:

      #
      # Checkout
      # Checks-out the repository
      #

      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      #
      # Dependencies
      # Install required runtime modules
      #

      - task: PowerShell@2
        displayName: "Dependencies"
        inputs:
          targetType: "inline"
          script: |
            Install-Module -Name AzOps -Force

      #
      # Connect
      # Authenticate Azure context
      #

      - task: PowerShell@2
        displayName: "Connect"
        inputs:
          targetType: "inline"
          script: |
            $credential = New-Object PSCredential -ArgumentList $(ARM_CLIENT_ID), (ConvertTo-SecureString -String $(ARM_CLIENT_SECRET) -AsPlainText -Force)
            Connect-AzAccount -TenantId $(ARM_TENANT_ID) -ServicePrincipal -Credential $credential -SubscriptionId $(ARM_SUBSCRIPTION_ID)

      #
      # Diff
      # List index changes
      #

      - task: Bash@3
        displayName: "Diff"
        inputs:
          targetType: "inline"
          script: |
            echo $(git diff --name-status HEAD^ HEAD)
            git diff --name-status HEAD^ HEAD > /tmp/diff.txt

      #
      # Deploy
      # Initial deployment of any index changes
      #

      - task: PowerShell@2
        displayName: "Deploy"
        inputs:
          targetType: "inline"
          script: |
            Import-PSFConfig -Path settings.json -Schema MetaJson
            Initialize-AzOpsEnvironment
            $diff = Get-Content -Path /tmp/diff.txt
            $module = Get-Module -Name AzOps
            $module.Invoke({ Invoke-AzOpsChange -ChangeSet $diff })
            Get-Job | Remove-Job -Force
