---
name: "AzOps - Validate"

#
# Triggers
# Automated triggers are configured via Branch Policies
# within Azure Repos. It's also recommended to manually
# disable CI triggers with overrides.
#

trigger: none

variables:
    
  #
  # Shared variables
  # Include shared variables from the 'vars.yml' file
  # to not have to repeat them in every pipeline.
  #

  - template: .templates/vars.yml

jobs:

  - job: validate

    #
    # Validate
    #

    displayName: "Validate"
    pool:
      vmImage: "ubuntu-20.04"

    steps:
  
      #
      # Shared steps
      # Include shared steps from the 'shared.yml' file
      # to not have to repeat them in every pipeline.
      #
      
      - template: .templates/sharedSteps.yml

      #
      # Validate
      # Run what-if deployment on any templates changed
      # in the last commit
      #
      
      - template: .templates/validate-deploy.yml
        parameters:
          deploy: false

      #
      # Results
      # Post results as a comment to the pull request.
      #

      - task: PowerShell@2
        displayName: 'Results'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        inputs:
          targetType: "inline"
          script: |
            if (Test-Path "/tmp/OUTPUT.md") {
              $uri = "$(System.CollectionUri)/$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=6.0"
              Invoke-RestMethod `
                -Method Post `
                -ContentType "application/json;charset=utf-8" `
                -Headers @{ "Authorization" = "Bearer $(System.AccessToken)" } `
                -Body (@{
                  "comments" = @(
                      @{ "parentCommentId" = 0; "content" = "$(Get-Content -Path /tmp/OUTPUT.md -Raw)"; "commentType" = 1 }
                  )
                  "status"  = 1
                } | ConvertTo-Json) `
                -Uri $uri
            }
