name: "AzOps - Pull"

on:
  workflow_dispatch:

env:
  credentials: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  pull:
    name: "Pull"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          path: azops-starter

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          repository: ljtill/azops
          path: azops
          ref: dev

      - name: "List"
        run: |
          Get-ChildItem -Path "/usr/share/az*"
        shell: pwsh

      - name: "Install"
        run: |
          Install-Module -Name @("Az.Accounts", "Az.Resources", "PSFramework") -Force
        shell: pwsh

      - name: "Connect"
        run: |
          $credential = New-Object System.Management.Automation.PSCredential `
            -ArgumentList "$env:ARM_CLIENT_ID", ("$env:ARM_CLIENT_SECRET" | ConvertTo-SecureString -AsPlainText -Force)
          Connect-AzAccount `
            -TenantId "$env:ARM_TENANT_ID" `
            -ServicePrincipal `
            -Credential $credential `
            -SubscriptionId "$env:ARM_SUBSCRIPTION_ID"
        shell: pwsh

      - name: "Import"
        run: |
          Import-Module ./src/AzOps.psd1
        shell: pwsh
        working-directory: azops
