name: "AzOps - Pull"

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  pull:
    name: "Pull"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          path: azops-starter
          fetch-depth: 0

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          path: azops
          fetch-depth: 0
          repository: ljtill/azops
          ref: dev

      - name: "Install"
        run: |
          Install-Module -Name @("Az.Accounts", "Az.Resources", "PSFramework") -Force
        shell: pwsh

      - name: "Connect"
        run: |
          $clientId = $env:ARM_CLIENT_ID
          $clientSecret = $env:ARM_CLIENT_SECRET
          $tenantId = $env:ARM_TENANT_ID
          $subscriptionId = $env:ARM_SUBSCRIPTION_ID
          $credential = New-Object System.Management.Automation.PSCredential `
            -ArgumentList $clientId, (ConvertTo-SecureString -String $clientSecret -AsPlainText -Force)
          Connect-AzAccount `
            -TenantId $tenantId `
            -ServicePrincipal `
            -Credential $credential `
            -SubscriptionId $subscriptionId
        shell: pwsh

      - name: "Invoke"
        run: |
          Import-Module ./azops/src/AzOps.psd1
          $VerbosePreference = "Continue"
          Initialize-AzOpsRepository -SkipPolicy -SkipResourceGroup -Verbose
        shell: pwsh
