name: "AzOps - Pull"

on:
  workflow_dispatch:

jobs:
  pull:
    name: "Pull"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          path: azops-starter

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          repository: ljtill/azops
          path: azops
          ref: dev

      - name: "List"
        run: |
          Get-ChildItem -Path "/usr/share/az*"
        shell: pwsh

      # - name: "Connect"
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: "Install"
      #   run: |
      #     Install-Module -Name @("PSFramework") -Force
      #   shell: pwsh
      # - name: "Import"
      #   run: |
      #     Import-Module ./src/AzOps.psd1
      #   shell: pwsh
      #   working-directory: azops
