---
name: 'AzOps - Configure'

on:
  workflow_dispatch:

jobs:

  configure:

    name: 'Configure'
    runs-on: ubuntu-20.04
    steps:

      - name: 'Configure'
        run: |
          git config user.name github-actions
          git config user.email action@github.com

      - name: 'Create'
        run: |
          mkdir .github/workflows

      - name: 'Copy'
        run: |
          cp -R .github/templates/simple/ .github/workflows/

      - name: 'Remove'
        run: |
          rm -rf .pipelines/

      - name: 'Add'
        run: |
          git add .

      - name: 'Commit'
        run: |
          git commit -m 'Initial configuration'

      - name: 'Push'
        run: |
          git push origin main