---
name: "AzOps - Validate"

on:
  #
  # Pull Request
  # Upon the creation of a new Pull Request in the root folder
  # this workflow will execute.
  #

  pull_request:
    paths:
      - "root/**"

env:
  #
  # Credentials
  #

  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  validate:
    #
    # Validate
    #

    name: "Validate"
    runs-on: ubuntu-20.04

    steps:
      #
      # Checkout
      # Checks-out the repository
      #

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #
      # Shared steps
      # Include shared steps from the 'shared.yml' file
      # to not have to repeat them in every pipeline.
      #

      - name: 'Sharedsteps'
        uses: ./.github/.templates/sharedSteps
   
      #
      # Validate
      # Run what-if deployment on any templates changed
      # in the last commit
      #

      - name: 'Validate'
        with:
          deploy: false
          name: 'Validate'
        uses: ./.github/.templates/validate-deploy
      
      #
      # Results
      #

      - name: "Results"
        shell: bash
        run: |
          if [ -f /tmp/OUTPUT.md ]; then
            gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/OUTPUT.md
          else
            echo "There are no results, so no comments are posted. For further information please look into the validate step."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
