---
name: "AzOps - Validate"

on:
  #
  # Pull Request
  # Upon the creation of a new Pull Request in the root folder
  # this workflow will execute.
  #

  pull_request:
    paths:
      - "root/**"
      
#
# Permissions required for the pipeline to interact with repo and federated credentials
#

permissions:
    id-token: write
    contents: write
    pull-requests: write

env:
  #
  # Credentials
  #

  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  AZOPS_MODULE_VERSION: ${{ secrets.AZOPS_MODULE_VERSION }}
  APPLICATIONINSIGHTS_CONNECTIONSTRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTIONSTRING }}

  #
  # modulesFolder
  # To enable caching of PowerShell modules between
  # runs, the modules are stored in a modules folder
  # that can be cached.
  #
  
  modulesFolder: "~/.local/share/powershell/Modules"

jobs:
  validate:
    #
    # Validate
    #

    name: "Validate"
    runs-on: ubuntu-24.04
        
    #
    # Environment if using Federated Credentials 
    # https://github.com/azure/azops/wiki/oidc
    #

    # environment: prod 


    steps:
      #
      # Checkout
      # Checks-out the repository
      #

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      #
      # Shared steps
      # Include shared steps from the 'shared.yml' file
      # to not have to repeat them in every pipeline.
      #

      - name: 'Shared steps'
        uses: ./.github/actions/sharedSteps
   
      #
      # Validate
      # Run what-if deployment on any templates changed
      # in the last commit
      #

      - name: 'Validate'
        with:
          deploy: false
          name: 'Validate'
        uses: ./.github/actions/validate-deploy
      
      #
      # Results
      #

      - name: "Results"
        if: always()
        shell: bash
        run: |
          if [ -f /tmp/OUTPUT.md ]; then
            gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/OUTPUT.md
          else
            echo "There are no results, so no comments are posted. For further information please look into the validate step."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
